[build]
  command = """
    pip install poetry &&
    poetry install &&
    poetry run blog build
  """
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.13"
  POETRY_VERSION = "1.7.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
